### PR TITLE
I have added a project named- Image background remover. It is fully wokring, PLease merge it.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by diwakar1593** [comment]
@Igdtuwresource please update readme file

**Comment by ghost** [comment]
I have added now. Sorry for any incovinience caused.

**Comment by diwakar1593** [comment]
@Igdtuwresource Update my readme. check it out

**Comment by ghost** [comment]
image
do i need to make changes in this also?
I am little bit confused .
can you please provide more clarification.

**Comment by ghost** [comment]
i have updated main readme also. please check

**Comment by ghost** [comment]
Please merge my also . If any issue is still there, please tell. Please

**Comment by diwakar1593** [comment]
@Igdtuwresource Thanks

**Pull request merged**
